### ISSUE TITLE
Route Waypoints

### ISSUE THREAD

**Issue by myatrakos** [Keagansed/CarPool#83]
Add way-points, at set distances, to routes. This is going to be used to cross check routes to see whether they are eligible to be recommended for another users route.

**Comment by MyronOuyang** [comment]
Copy the waypoint array
Do some text cleanup (remove the everything except latlng coords)
Get text into following format: lat,lng eg: 25.767368,-80.18930
Copy into this site: https://www.darrinward.com/lat-long/?id=5b39c880105107.57632357
